version: "3.1"
services:
    www:
        container_name: www
        build: .
        ports: 
            - 80:80
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default

    db:
        container_name: mariadb
        image: mariadb:10.3
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: local
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        links:
            - db
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

volumes:
    persistent:
